version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    networks:
      - conec
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment: 
      - MYSQL_DATABASE_NAME=${MYSQL_DATABASE_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PORT=3306
      - MYSQL_HOST=db
    restart: always
    networks:
      - conec
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    networks:
      - conec

    ports:
      - "4321:4321"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      

volumes:
  db_data:

networks:
  conec:
