version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    networks:
      - conec
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment: 
      - DB_DATABASE=database
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
      - DB_PORT=3306
      - DB_HOST=db
    restart: always
    networks:
      - conec
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    networks:
      - conec
    ports:
      - "4321:4321"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      

volumes:
  db_data:

networks:
  conec:
