version: '3.3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports: 
      - $DB_PORT:$DB_PORT
    command: [--max-allowed-packet=1000]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=$DB_USERNAME
      - PMA_PASSWORD=$DB_PASSWORD
      - PMA_PORTS=$DB_PORT
    ports:
      - 5050:80
    depends_on:
      - db