version: '3.3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_PASSWORD: teste
      MYSQL_USER: teste
      MYSQL_DATABASE: teste
    ports: 
      - 3306:3306
