FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y build-essential default-libmysqlclient-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /app/

ENV PYTHONPATH /app:$PYTHONPATH

EXPOSE 8000

CMD ["gunicorn", "--chdir", "/app", "luminacritics.wsgi:application", "--bind", "0.0.0.0:8000"]
